### ISSUE TITLE
Import Failed (onnxruntime)

### ISSUE THREAD

**Issue by mattwalewangko** [shiimizu/ComfyUI-PhotoMaker-Plus#38]
I've tried multiple ways of installing onnxruntime and insightface and at least one of them seems to still be in conflict.

Traceback (most recent call last):
  File "C:\Users\mattw\AI\Local_AI_Photos\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\__init__.py", line 8, in <module>
    import onnxruntime
ModuleNotFoundError: No module named 'onnxruntime'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mattw\AI\Local_AI_Photos\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\mattw\AI\Local_AI_Photos\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PhotoMaker-Plus\__init__.py", line 1, in <module>
    from .photomaker import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\Users\mattw\AI\Local_AI_Photos\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PhotoMaker-Plus\photomaker.py", line 20, in <module>
    from .insightface_package import FaceAnalysis2, analyze_faces, insightface_loader
  File "C:\Users\mattw\AI\Local_AI_Photos\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PhotoMaker-Plus\insightface_package.py", line 3, in <module>
    from insightface.app import FaceAnalysis
  File "C:\Users\mattw\AI\Local_AI_Photos\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\__init__.py", line 10, in <module>
    raise ImportError(
ImportError: Unable to import dependency onnxruntime.

Cannot import C:\Users\mattw\AI\Local_AI_Photos\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PhotoMaker-Plus module for custom nodes: Unable to import dependency onnxruntime.

**Comment by shiimizu** [comment]
You need both `onnxruntime` and `onnxruntime-gpu`
In a terminal window, run something like:
```shell
ComfyUI_windows_portable\python_embeded\python.exe -m pip install onnxruntime
```

**Comment by mattwalewangko** [comment]
I feel dumb for running that command in like 7 different places and then it works now, still, thank you <3

**Comment by mattwalewangko** [comment]
I feel dumb for running that command in like 7 different places and then it works now, still, thank you <3
